CREATE OR REPLACE DATABASE LAB_6_DB;
CREATE OR REPLACE SCHEMA LAB_6_DB.PUBLIC;
CREATE OR REPLACE TABLE LAB_6_DB.PUBLIC.BEFORE(
	   WELL_NAME VARCHAR(256) NOT NULL,
	   API_NO VARCHAR(256) NOT NULL,
	   COUNTY_STATE VARCHAR(256),
	   WELL_SHL VARCHAR(256),
	   DATUM VARCHAR(256),
	   DATE_STIMULATED VARCHAR(256),
	   STIMULATED_FORMATION VARCHAR(256),
	   TOP_FT VARCHAR(256),
	   BOTTOM_FT VARCHAR(256),
	   STIMULATED_IN VARCHAR(256),
	   STIMULATED_STATES VARCHAR(256),
	   VOLUME_ VARCHAR(256),
	   VOLUME_UNITS VARCHAR(256),
	   TYPE_TREATMENT VARCHAR(256),
	   ACID_PCT VARCHAR(256),
	   LBS_PROPPANT VARCHAR(256),
	   MAX_TREATMENT_PRESSURE_PSI VARCHAR(256),
	   MAX_TREATMENT_RATE_BBLS_MIN VARCHAR(256),
	   DETAILS VARCHAR(256),
	   PRIMARY KEY (WELL_NAME, API_NO)
);

CREATE OR REPLACE TABLE LAB_6_DB.PUBLIC.AFTER(
	   WELL_NAME VARCHAR(256) NOT NULL,
	   API_NO VARCHAR(256) NOTac NULL,
	   OPERATOR VARCHAR(256),
	   WELL_STATUS VARCHAR(256),
	   WELL_TYPE VARCHAR(256),
	   CLOSEST_CITY VARCHAR(256),
	   LATITUDE VARCHAR(256),
	   LONGITUDE VARCHAR(256),
	   OIL_PRODUCED VARCHAR(256),
	   GAS_PRODUCED VARCHAR(256),
	   PRIMARY KEY (WELL_NAME, API_NO)
);
