CREATE OR REPLACE DATABASE LAB_6_DB;
CREATE OR REPLACE SCHEMA LAB_6_DB.PUBLIC;
CREATE OR REPLACE TABLE LAB_6_DB.PUBLIC.BEFORE(
	   WELL_NAME VARCHAR(64),
	   API_NO VARCHAR(64),
	   PRIMARY KEY (WELL_NAME, API_NO)
);

CREATE OR REPLACE TABLE LAB_6_DB.PUBLIC.AFTER(
	   WELL_NAME VARCHAR(64) NOT NULL,
	   API_NO VARCHAR(64) NOT NULL,
	   OPERATOR VARCHAR(64) NOT NULL,
	   WELL_STATUS VARCHAR(64) NOT NULL,
	   WELL_TYPE VARCHAR(64) NOT NULL,
	   CLOSEST_CITY VARCHAR(64) NOT NULL,
	   LATITUDE VARCHAR(64) NOT NULL,
	   LONGITUDE VARCHAR(64) NOT NULL,
	   OIL_PRODUCED VARCHAR(64),
	   GAS_PRODUCED VARCHAR(64),
	   -- WELL_NAME, API_NO canbe wrong in BEFORE
	   PRIMARY KEY (WELL_NAME, API_NO)
);
